# Site settings
title: Wufujian Blog
SEOTitle: 伍福建的博客 | Ng-Fukgin Blog
header-img: img/home-bg.jpg
email: wfj.0000@gmail.com
#description: "关于程序与设计、黑客与画家 | 黄玄，Web & Mobile Lover，Software Engineer，UX Designer | 这里是 @Hux黄玄 的个人博客，与你一起发现更大的世界。"
keywords: "伍福建, wufujian, Fujian,ng-fukgin"
url: "https://ng-fukgin.github.io"            # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username:     u/7492756401
#zhihu_username:     wfj-52
github_username:    ng-fukgin
gitee_username:    ng-fukgin
#twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx
address_l:    新界大埔科学园19w
scholar:    zMG1mUIAAAAJ


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: wufujian

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'G-SK6SLBK11B'            # Format: UA-xxxxxx-xx
ga_domain: https://ng-fukgin.github.io/



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "伍福建，一条咸鱼 <br> WUFUJIAN，a salted fish."
#sidebar-avatar: https://github.com/Huxpro.png # use absolute URL, seeing it's used in both `/` and `/about/`
sidebar-avatar: /img/wufujian.jpg # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "Raymond",
        href: "https://happyraymond.github.io/"
    },{
        title: "邬邬邬邬政东",
        href: "https://wu-zhengdong.github.io/"
    },{
        title: "郑煜钒 ",
        href: "https://YufanZheng.github.io"

    },{
      title: "Jessie",
        href: "https://zeqiong-06.github.io/"
    }
]
